"use client";

import Header from "@/app/admin/components/Header";
import React, { useRef } from "react";
import "../globals.css";
//import { Metadata } from "next";


import { SiteProvider } from "@/SiteContext/SiteProvider";
import SideBarBase from "./SideBarBase";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

 

  

  return (
    <html lang="de">
      <body>
        <SiteProvider>
          <main className="relative flex">
<SideBarBase />

            <div className="w-full flex flex-col">
              <div className="">
                <Header />
              </div>
              <div className="w-full flex flex-col p-5 mt-12 bg-slate-100 h-screen">
                {children}
              </div>
            </div>
          </main>
        </SiteProvider>
      </body>
    </html>
  );
}
